// CMC SET INFO: text shown in the Set Info popup. Keys are the set name, upper-cased with non-alphanumerics replaced by "_".
const setInfo = {
    "50S_CULT_CLASSICS": "A trip back to the golden age of sci-fi and creature features. This set celebrates the imagination, charm and occasional madness of 1950s cult cinema.",
    "BANNED": "Too shocking, too controversial or simply too strange. This set brings together films that pushed boundaries and earned their place on the wrong side of approval.",
    "BATTLE_BEYOND_THE_STARS": "Space battles, rogue heroes and intergalactic adventure take centre stage in this sci-fi spectacle packed with action, ambition and classic cult charm.",
    "BD": "BD earned a Mythic Bubblegum card and sat on it for a while, basking in the pinky glow.. then they traded it in for this magnificent bastard of a card!",
    "BIG_TROUBLE_IN_LITTLE_CHINA": "Magic, monsters and mayhem collide in this high-energy cult classic. This set brings together martial arts, mysticism and pure chaos in a world where anything can happen.",
    "BLACK_CHRISTMAS": "The calls are coming from inside the house… This set captures the chilling atmosphere and slow-building dread of one of horror’s most influential and unsettling seasonal nightmares.",
    "CATACOMBS_CREATURES": "Deep below the surface, something is waiting. This set explores the dark, the hidden and the monstrous creatures lurking in places best left undisturbed.",
    "CHILDREN_SHOULDNT_PLAY_WITH_DEAD_THINGS": "This set was scheduled for release in June 2025, but was abandoned preceeding a lengthy hiatus. It was never completed, but the 21 cards that were finished are available here to view.",
    "CHOPPING_MALL": "When shopping goes wrong, it goes very wrong. Killer robots, late-night retail and pure chaos combine in this set celebrating one of the most entertainingly absurd cult horrors around.",
    "CMC_VAULT_SHELL_COMMANDS_LIST": "Not a movie card series, but a gateway.. this collection documents the commands, secrets and hidden functions that power the system itself.",
    "COPS_N_ROBBERS": "Crime, chaos and high-stakes chases define this set. From law enforcers to outlaws, it’s all about the tension between those who chase and those who run.",
    "CREEPSHOW": "Five tales of comic-book terror, one grinning Creep. This set gathers the twisted revenge, hungry fungus and cereal-based tragedy of Romero and King's EC Comics love letter.",
    "CULTOONS": "Animation gets weird. This set dives into the stranger side of animated cult classics, where bold visuals and offbeat storytelling take centre stage.",
    "CULT_CARNAGE": "Engines roar, tyres scream and something always ends up in flames. This set celebrates killer cars, rogue machines and the high-speed mayhem of the open road.",
    "CULT_LEADERS": "Charisma, control and dangerous influence. This set focuses on figures who command attention and shape the worlds around them — for better or worse.",
    "CULT_VILLAINS": "These cards were intended to mimic the 1938 Hamilton Gum v289 vintage cards. Initial releases of these cards proved unpopular, and the set was ultimately abandoned. Card #5 of this set 'Nurse Ratched' was never released on Bluesky. ",
    "DAUGHTERS_OF_DARKNESS": "Elegant, eerie and dripping with atmosphere, this set explores seduction, mystery and the darker side of desire in a world where nothing is quite what it seems.",
    "DAVID_LYNCH_SERIES": "Dream logic, unsettling imagery and stories that refuse to explain themselves. This set explores the surreal and unforgettable world of David Lynch.",
    "ECLECTIC_COLLECTOR": "Eclectic Collector fought tooth-and-nail for a Mythic Bubblegum card, missing out on several occasions.. so when they got one, they put it to good use!",
    "ERIN_A_DOYLE": "Erin A Doyle earned a Mythic Bubblegum card for her suggestion of 'Dark Shadows', which inspired an entire set!",
    "EXPLODING_HELICOPTER": "If it's got rotor blades, it's going to go boom. This set is dedicated to the proud and fiery tradition of the exploding helicopter.",
    "FAUX_MOTION": "Not everything is what it seems. This set plays with illusion, perception and visual trickery, capturing moments where reality feels just slightly off.",
    "FRIGHT_CLUB_FEATURES_I": "Welcome to the first screening. This set brings together a curated selection of horror highlights, packed with unforgettable moments that define the Fright Club experience.",
    "FRIGHT_CLUB_FEATURES_II": "The second screening raises the stakes. More scares, more chaos and even stranger moments from the depths of cult horror cinema shown on Fright Club.",
    "FRIGHT_CLUB_FEATURES_III": "The horror continues. This set delivers another round of terrifying, bizarre and unforgettable moments straight from the Fright Club vault.",
    "FRIGHT_CLUB_FEATURES_IV": "The fourth screening of Fright Club Features pushes things even further. Darker, stranger and packed with moments that refuse to leave your mind.",
    "FRIGHT_CLUB_FEATURES_V": "The fifth instalment of Fright Club, packed with creature features, cursed locations and deep-cut horror. Expect sewer dwellers, giant birds and a whole lot of rubber.",
    "FRIGHT_CLUB_FEATURES_VI": "Fright Club returns for a sixth outing. This set is still growing, so check back for more horror and sci-fi favourites.",
    "FUTURE_SHOCKS": "The future isn’t always bright. This set explores dystopian worlds, advanced tech and the consequences of progress gone wrong.",
    "GARTH_ARIZONA": "Garth Arizona creates a wonderful array of LEGO Kolchak sequences and stories.. they used their Mythic Bubblegum card to bring one of them to life through Faux-Motion!",
    "GIALLO_GELATO": "Stylish, violent and dripping with colour, this set celebrates the unique flair of giallo cinema — mystery, murder and unforgettable visuals.",
    "GOTHIK_GHOULS": "Candlelight, capes and Euro-horror seduction. This set drapes itself in the lush, sensual and strangely dreamy side of 1970s vampire cinema.",
    "HAMMER_SERIES": "Technicolor blood, heaving bosoms and gothic castles. This set pays tribute to the legendary studio that gave monsters a fresh coat of crimson.",
    "HAUNTED_HOUSES": "Some places don’t forget. This set gathers eerie locations filled with spirits, secrets and the lingering presence of something unseen.",
    "HEXY_BEASTS": "Magic and monsters collide in this collection of strange and supernatural creatures, where spells and chaos go hand in hand.",
    "HOUSEPIG": "Master of the Mythic Bubblegum, these card requests made by Housepig consist of massive deep-cuts, featuring movies rarely seen.. or heard of!",
    "H_P_LOVECRAFT_SERIES": "Ancient horrors and cosmic dread define this set, where humanity is small, knowledge is dangerous and something vast waits just beyond understanding.",
    "INVADERS": "They came from beyond — and they’re not leaving. This set explores alien encounters, invasions and the fear of something watching from the skies.",
    "KICKASS_KARATE": "Originally designed for the #B9 Mythic Bubblegum trade-in card, we couldn't let this one sit on the shelf.. so now there's an entire set of sword-swinging, ass-kicking cards!",
    "KILLER_QUEENS": "Deadly, stylish and impossible to ignore. This set celebrates powerful female figures who take control and leave a lasting impression.",
    "KULT_KAIJU": "Giant monsters, massive destruction and city-crushing chaos. This set is all about scale, spectacle and creatures that refuse to stay hidden.",
    "MARIO_BAVA_SERIES": "A master of atmosphere and visual style. This set highlights the bold colours, shadows and unforgettable imagery of Mario Bava’s work.",
    "MIDNIGHT_CULT_SERIES_I": "The first wave of late-night classics. This set captures the energy of films that found their audience after dark — strange, bold and impossible to ignore.",
    "MIDNIGHT_CULT_SERIES_II": "The late-night journey continues. More strange, bold and unforgettable moments from films that thrive in the dark hours.",
    "MIDNIGHT_CULT_SERIES_III": "Deeper into the night we go. This set brings even more surreal, chaotic and cult-defining moments to the surface.",
    "MIDNIGHT_CULT_SERIES_IV": "The fourth stretch of the midnight experience. Strange, intense and impossible to forget, these films leave a lasting mark.",
    "MONSTER_MACHINES": "When metal turns monstrous. This set features vehicles and machines that go beyond control and become something far more dangerous.",
    "MRBUNDREN": "Yet another winner of a CMC competition, this niche request was laid over an existing series and set on a foil card. The cries of 'Sword Boy!!' forever immortalised!",
    "MUSICAL_MADNESS": "When speaking just isn't enough. This set belts out the glam, grit and outright weirdness of cult cinema's most unforgettable musical numbers.",
    "MYTHO_LITHO": "Vintage lithography, faked with love. This set gives the mythic heroes and hard men of cult cinema the look of aged, hand-printed posters from another era.",
    "NEON_NIGHTMARES": "Glowing signs, wet streets and something lurking in the glare. This set soaks cult cinema's darker side in neon.",
    "OZPLOITATIONS": "Wild, gritty and uniquely Australian. This set celebrates the bold energy and fearless storytelling of Ozploitation cinema.",
    "PHELT_PHANTASIES": "Soft textures meet strange ideas in this offbeat collection. Playful, surreal and just a little unsettling.",
    "PSEUDO_CLUEDO": "Mystery, suspects and secrets collide in this playful set inspired by classic whodunnit storytelling with a cult twist.",
    "REPO_MAN": "Punk attitude meets sci-fi weirdness in this offbeat collection. Repo men, glowing trunks and government secrets collide in a set that captures the strange energy of cult cinema at its most unpredictable.",
    "RE_ANIMATOR": "Herbert West has a serum, a deadline and absolutely no bedside manner. This set brings back the gooey, gleefully gruesome chaos of Stuart Gordon's Lovecraft-inspired classic.",
    "RIP_OFFS": "Inspired by… or suspiciously similar to. This set explores films that borrowed heavily and created something strangely unique in the process.",
    "ROLLERBALL_STICKERS_RUB_OFFS": "Unfathomable amounts of work went into the designs of these cards, a re-work of the Pac-Man Stickers & Rub-offs set from 1980. So much work in fact, that the set was abandoned due to exhaustion. Only 5 were ever made.",
    "SAM_CRUISE_AGENCY": "These cards were based on the Topps 'Superman' series and were created for the CMC alt-account 'Sam Cruise Agency'. The account is now pretty much abandoned, but these ZX Spectrum themed cards live on. Over 100 were made in total.",
    "SHAWS_RIDLER": "Deciphered and shared the PIN code to get into the CMC vault as part of a competition, this Mythic Bubblegum card winner exchanged theirs for a spicy gothic vampire card!",
    "SHAW_BROTHERS_SERIES": "Flying fists, killer venoms and masters of the deadly blade. This set honours the Shaw Brothers studio and the kung-fu classics that shaped a genre.",
    "SIEVETRONIX": "Winner of 'half' of the CMC This Is Spinal Tap 'Pap' Quiz, Sievetronix almost immediately traded his Mythic Bubblegum card in for this absolute beauty.",
    "SINGLE_SCOOPS": "Some films are so traumatic they can only be endured once. This set collects those unforgettable one-time-only experiences, so you never have to sit through them again.",
    "SLASHERS_SERIES": "Masks, machetes and teens making terrible decisions. This set lines up the killers, the final girls and the bloody blueprints of the slasher boom.",
    "SORCERER": "Four desperate men, two trucks and a payload that could go off at any moment. This set follows Friedkin's sweat-soaked journey through the jungle, one unstable bump at a time.",
    "SPEKTRALIZED": "Loading... please wait. This set hybridises ZX Spectrum loading screens with movie stills, colour clash, scan lines and all.",
    "SPORTS_LEGENDS": "Bowling lanes, prison yards and kung-fu football pitches. This set celebrates the unlikely champions and wonderfully strange sporting heroes of cult cinema.",
    "STICKER_SHOTS": "Peel, stick and unleash. Inspired by classic sticker cards, this set is full of monsters, mayhem and 80s favourites ready to go on your school bag.",
    "SUPER_SIDEKICKS": "Every hero needs someone watching their back. This set shines a spotlight on cult cinema's finest companions, helpers and the odd monstrous brother in a basket.",
    "TALES_FROM_THE_CRYPT": "Welcome, boils and ghouls. This set digs up the twisted cast of the EC Comics-inspired horror anthology, where everybody gets exactly what's coming to them.",
    "THEY_LIVE": "Obey, consume, conform… or start seeing things as they really are. This set dives into hidden messages, alien control and the fight to break free from a world that isn’t what it seems.",
    "THE_HUNGER": "Eternal youth has a price. This set captures the cold, stylish seduction of Tony Scott's vampire tale, from smoky nightclubs to the slow decay of forever.",
    "THE_NINTH_CONFIGURATION": "Part war film, part psychological spiral, this set explores madness, morality and the thin line between them. Expect intense moments, strange humour and conversations that linger long after they end.",
    "THIS_IS_SPINAL_TAP": "Turn it up to eleven. This set celebrates the chaos, comedy and sheer absurdity of rock ‘n’ roll excess, where everything goes wrong in the most entertaining way possible.",
    "ULTIMATE_SERIES": "The definitive list. This set counts down the top 100 cult movies of all time, each one earning its place with an extra helping of attitude.",
    "VIDEODROME": "Long live the new flesh. This set dives into media, control and the blurring line between screen and reality in one of cult cinema’s most iconic visions.",
    "VINCENT_PRICE_SERIES": "That voice. That moustache. That menace. This set pays tribute to the one and only Vincent Price, the undisputed king of velvet-voiced horror.",
    "VOID_WARS": "In space, no one can hear you question your life choices. This set drifts through the bleak, haunted and hostile corners of cult sci-fi.",
    "WAKE_IN_FRIGHT": "Sun-soaked landscapes hide something far more unsettling in this brutal descent into isolation. This set captures the heat, the tension and the slow unravelling of a man pushed too far.",
    "WAX_PACK_GLAM": "WPG has an unlimited supply of Mythic Bubblegum cards, but this one was traded-in for a very special Birthday card directly from Sybil Danning herself (sort of)!",
    "WILD_THINGS": "A set full of animals and insects that dominate the screen at every turn, and wreak havoc amongst the world and its inhabitants!",
    "WORLD_CULT_SERIES": "A trip around the globe, one cult classic at a time. This set picks a film from every corner of the map, proving that weird, wonderful cinema knows no borders.",
    "ZOMBIE_NATION": "The dead don’t stay down. This set is packed with shambling horrors, outbreaks and the relentless march of the undead."
};
